#!/usr/bin/env bash -e

scriptdir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
pushd $scriptdir > /dev/null

ci_ip=$(../terraform/tf output -no-color ip_address)

# we need an increased timeout, the droplet might not be completely ready yet
ansible-playbook main.yml -i hosts --extra-vars "ci_ip=$ci_ip" --timeout=60 "$@"

popd > /dev/null
